services:
  modeloman:
    build: .
    container_name: modeloman
    environment:
      GRPC_ADDR: ":50051"
      DATA_FILE: /data/modeloman.db.json
      AUTH_TOKEN: ""
    ports:
      - "50051:50051"
    volumes:
      - ./data:/data
    restart: unless-stopped
